# Generated by Django 5.2.6 on 2025-09-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_prize', models.FloatField()),
                ('discount_prize', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('ML', 'Milk'), ('LS', 'Lassi'), ('GH', 'Ghee'), ('IC', 'Icecream'), ('CZ', 'Cheesse')], max_length=2)),
                ('product_images', models.ImageField(upload_to='product')),
            ],
        ),
    ]
