# Generated by Django 5.2.6 on 2025-09-06 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_prize',
            new_name='discounted_price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_images',
            new_name='product_image',
        ),
    ]
